# Generated by Django 4.2.3 on 2023-11-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_booking_name_remove_menu_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
    ]
