# Generated by Django 4.2.3 on 2023-11-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_booking_user_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guest',
        ),
    ]
